### ISSUE TITLE
Feature request: doing this w/o public cloud

### ISSUE THREAD

**Issue by cccsss01** [IMESHinc/webinar#5]
Love what you have here, any chance you have an idea how to do  this with your own external load balancer?  I.E. not relying on EKS or GKE, but an ELB?

**Comment by malti24** [comment]
@cccsss01 We may use Node port. However, can you specify  your setup a bit and which case are you trying to implement(out of several webinars code) to help you better? Also, You can reach out to us directly at contact@imesh.ai

Note: This is old repo and would be archived in future. For latest codes, use https://github.com/imesh-ai/webinar
